href:
  rails: "http://railstutorial.org/"
  rails_news: "https://news.railstutorial.org/"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  michaelhartl: "https://www.michaelhartl.com/"
  rubyonrails: "https://rubyonrails.org/"

user:
  name:
    max_length: 20
  email:
    min_length: 20
    max_length: 255
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  password:
    min_length: 6
  helper:
    size: 80
  size:
    max_length: 80
  edit:
    link_href: "https://gravatar.com/emails"
  size_gravatar_follow: 30

micropost:
  size: 50
  image_path: ["image/jpeg", "image/gif", "image/png", "image/jpg"]
  less_than: 5
  max_length_content: 140
  resize_to_limit: [500, 500]

shared:
  micropost_form:
    image_path: "image/jpeg,image/gif,image/png,image/jpg"

time_expired_email: 2
number_row_page: 10
