href:
  rails: "http://railstutorial.org/"
  rails_news: "https://news.railstutorial.org/"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  michaelhartl: "https://www.michaelhartl.com/"
  rubyonrails: "https://rubyonrails.org/"
